### ISSUE TITLE
LLBlackBEEx的Bug

### ISSUE THREAD

**Issue by omscsamilcup** [lgc2333/LLSEPlugins#3]
/blackbe查询玩家ID不会出现任何记录

**Comment by omscsamilcup** [comment]
![Screenshot_20221015-181312_Minecraft.jpg](https://user-images.githubusercontent.com/112487226/195981259-0b2cd5a6-715c-4f92-aaa8-3bfe27c29eb9.jpg)![Screenshot_20221015-181319_Minecraft.jpg](https://user-images.githubusercontent.com/112487226/195981263-0cc8213e-53e6-4d55-b5ba-a2862e0fbf4c.jpg)

**Comment by lgc2333** [comment]
等我忙完其他项目再来修ll插件

**Comment by lgc2333** [comment]
看下好了没

**Comment by lgc2333** [comment]
> /blackbe查询玩家ID不会出现任何记录

az
`/blackbe`是用来查云端记录的，其中不包含本地黑名单

你应该用`/banlist`
