### ISSUE TITLE
CustomFormEx 可变绑定 & 输入检测

### ISSUE THREAD

**Issue by harry-xi** [lgc2333/LLSEPlugins#5]
- [x] 允许开发者修改和删除向CustomFormEx实例添加的控件
- [Not Planned] 为CustomForm的输入添加检查功能
  - 主要针对Input控件
  - 对与被检出的表单，向玩家弹出带提示的表单要求重新输入或者提供异常信息交由开发者自行处理

**Comment by lgc2333** [comment]
1st task resolved in https://github.com/lgc2333/LLSEPlugins/commit/acdbab22da1e59a9270c60c0a5fc1ce0e1054631
